#!/bin/bash
time $HOME/pgsql/bin/psql sim -c 'select count(*) from restaurantphone rp, addressphone ap where levenshtein_fast(rp.phone, ap.phone, 4) < 4;'

time $HOME/pgsql/bin/psql sim -c 'select count(*) from restaurantaddress ra, restaurantphone rp where levenshtein_fast(ra.name, rp.name, 3) < 3;'

time $HOME/pgsql/bin/psql sim -c 'select count(*) from restaurantaddress ra, addressphone ap where levenshtein_fast(ra.address, ap.address, 4) < 4;'
